name: CMake Build Matrix - v2

on:
  push:
    branches:
      -master

  pull_request:
    branches:
      - qtwebkit-dev-wip
      - qtwebkit-5.212

env:
  QT_VERSION: 5.14.1
  CMAKE_VERSION: 3.17.0-rc3
  NINJA_VERSION: 1.10.0
  CCACHE_VERSION: 3.7.7
  CACHE_PARTITION: 5.212
  HOST_N_CORES: 2
  NINJA_STATUS: "[%f/%t %o/sec] "
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "250M"
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CCACHE_HARDLINK: "true"
  QT_MODULES: "qtbase qtdeclarative qtlocation qtmultimedia qtsensors qtwebchannel"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Release", artifact: "macOS",
            os: macos-latest,
            build_type: Release,
          }
        - {
            name: "Windows MSVC Conan Release", artifact: "Windows-MSVC",
            os: windows-latest,
            build_type: Release,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - name: Sparse checkout
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        BRANCH="${GITHUB_REF/#refs\/heads\//}"
        # Following code is based on logs of actions/checkout@v2, with sparseCheckout stuff inserted in the middle
        echo "Syncing repository: $GITHUB_REPOSITORY"
        echo "Working directory is '$(pwd)' GITHUB_WORKSPACE=$GITHUB_WORKSPACE BRANCH=$BRANCH"
        git version
        git init $GITHUB_WORKSPACE
        git remote add origin https://github.com/$GITHUB_REPOSITORY
        git config --local gc.auto 0
        # Now interesting part
        git config core.sparseCheckout true
        # FIXME: hardcode! Cannot use .travis-sparse-checkout yet
        echo "/*" >> .git/info/sparse-checkout
        echo "!LayoutTests" >> .git/info/sparse-checkout
        git -c protocol.version=2 fetch --no-tags --prune --progress --depth=10 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
        git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH

    - name: Verify (Mac)
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: pip3 install jinja2 && Tools/qt/installed-files-checker.py --version=5.212.0 --os=macos --install_prefix="${{ steps.qt_mac.outputs.qt_dir }}" --template=Tools/qt/QtBinaryChecklist.txt --release --verbose

    - name: Verify (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: py -m pip install jinja2 && py Tools\qt\installed-files-checker.py --version=5.212.0 --os=windows --install_prefix="${{ steps.qt_win.outputs.qt_dir }}" --icu_version=65 --toolchain=msvc --template=Tools\qt\QtBinaryChecklist.txt --release --verbose
