name: Checker

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Release", artifact: "macOS",
            os: macos-latest,
            build_type: Release,
          }
        - {
            name: "Windows MSVC Conan Release", artifact: "Windows-MSVC",
            os: windows-latest,
            build_type: Release,
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel colorama
    - name: Verify (Mac)
      if: runner.os == 'macOS'
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: pip3 install jinja2 && python3 installed-files-checker.py --version=5.212.0 --os=macos --install_prefix="/mnt/c" --template=./QtBinaryChecklist.txt --release --verbose

    - name: Verify (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: py -m pip install jinja2 && py installed-files-checker.py --version=5.212.0 --os=windows --install_prefix="/mnt/c" --icu_version=65 --toolchain=msvc --template=./QtBinaryChecklist.txt --release --verbose
